version: "3.9"
services:
  # redpanda:
  #   image: docker.redpanda.com/redpandadata/redpanda:v24.1.7
  #   command: [ "redpanda", "start", "--overprovisioned", "--smp=1", "--memory=1G",
  #              "--reserve-memory=0M", "--node-id=0", "--check=false",
  #              "--kafka-addr=PLAINTEXT://0.0.0.0:9092", "--advertise-kafka-addr=PLAINTEXT://localhost:9092" ]
  #   ports: ["9092:9092"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes:
      - ./infra/initdb:/docker-entrypoint-initdb.d:ro

  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"    # Jaeger UI
      - "14250:14250"    # gRPC
      - "14268:14268"    # HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true   # enables OTLP ingestion on 4317/4318 (if you want direct)

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.102.1 #otel/opentelemetry-collector:0.102.1
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel/config.yaml:ro
    ports:
      - "4317:4317"      # OTLP gRPC (from apps)
      - "4318:4318"      # OTLP HTTP  (optional)
    depends_on:
      - jaeger
    restart: unless-stopped
