receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  memory_limiter:
    check_interval: 2s
    limit_percentage: 75
    spike_limit_percentage: 25
  batch:
  resourcedetection:
    detectors: [env]
    timeout: 2s
    override: false

exporters:
  otlp:
    endpoint: "jaeger:4317" #"jaeger:14250"
    tls:
      insecure: true
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:9464"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection]
      exporters: [otlp, logging]
